---
- name: include ubuntu extra work
  include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: ["resolv_conf"]

- name: create /etc/resolv.conf configuration
  become: true
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  tags: ["resolv_conf"]
